

services:
  # ==========================================================================
  # ---------------------------------- DB -------------------------------------
  # ==========================================================================
  GAMEMEMORY_DB:
    restart: unless-stopped
    tty: true
    image: arm64v8/postgres:15
    container_name: GAMEMEMORY_DB
    networks: [GameMemoryNetworkDB]
    ports: ["4002:5432"]
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=azerty007!
      - POSTGRES_DB=GAMEMEMORY_TT_DB
    volumes:
      - ./GAMEMEMORYDB:/var/lib/postgresql/data

  # ==========================================================================
  # ---------------------------------- BACK -----------------------------------
  # ==========================================================================
  GAMEMEMORY_BACK:
    tty: true
    restart: unless-stopped
    image: python:3.12-slim
    container_name: GAMEMEMORY_BACK
    depends_on: [GAMEMEMORY_DB, GAMEMEMORY_FRONT]
    working_dir: /app
    volumes: [./app/backend:/app]
    command: sh -c "sleep 10 && pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports: ["4001:8000"]
    networks:
      - GameMemoryNetworkDB
      - GameMemoryNetworkBridge
    env_file:
      - ./app/backend/.env

  # ==========================================================================
  # --------------------------------- FRONT -----------------------------------
  # ==========================================================================
  GAMEMEMORY_FRONT:
    tty: true
    image: node:20
    restart: unless-stopped
    container_name: GAMEMEMORY_FRONT
    networks: [GameMemoryNetworkBridge]
    working_dir: /home/node/app/
    volumes: [./app/frontend:/home/node/app/]
    environment:
       - VITE_BACKEND_URL=http://GAMEMEMORY_BACK:8000
    command: sh -c "npm i && npm run dev"
    ports: ["4000:5173"]

# ==========================================================================
# -------------------------------- NETWORKS ---------------------------------
# ==========================================================================
networks:
  GameMemoryNetworkDB:
    driver: bridge
  GameMemoryNetworkBridge:
    driver: bridge
